# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lifecycle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lifecycle.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0flifecycle.proto\"2\n\x10ModuleParameters\x12\x1e\n\nparameters\x18\x01 \x03(\x0b\x32\n.Parameter\"(\n\tParameter\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\r\n\x0bModuleStart\"\x0c\n\nModuleStop\"\x0f\n\rModuleRecover\"*\n\nConnection\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0e\n\x06\x63orurl\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODULEPARAMETERS = _descriptor.Descriptor(
  name='ModuleParameters',
  full_name='ModuleParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='ModuleParameters.parameters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=69,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Parameter.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Parameter.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=111,
)


_MODULESTART = _descriptor.Descriptor(
  name='ModuleStart',
  full_name='ModuleStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=126,
)


_MODULESTOP = _descriptor.Descriptor(
  name='ModuleStop',
  full_name='ModuleStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=140,
)


_MODULERECOVER = _descriptor.Descriptor(
  name='ModuleRecover',
  full_name='ModuleRecover',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=157,
)


_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Connection.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='corurl', full_name='Connection.corurl', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=201,
)

_MODULEPARAMETERS.fields_by_name['parameters'].message_type = _PARAMETER
DESCRIPTOR.message_types_by_name['ModuleParameters'] = _MODULEPARAMETERS
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['ModuleStart'] = _MODULESTART
DESCRIPTOR.message_types_by_name['ModuleStop'] = _MODULESTOP
DESCRIPTOR.message_types_by_name['ModuleRecover'] = _MODULERECOVER
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION

ModuleParameters = _reflection.GeneratedProtocolMessageType('ModuleParameters', (_message.Message,), dict(
  DESCRIPTOR = _MODULEPARAMETERS,
  __module__ = 'lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:ModuleParameters)
  ))
_sym_db.RegisterMessage(ModuleParameters)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:Parameter)
  ))
_sym_db.RegisterMessage(Parameter)

ModuleStart = _reflection.GeneratedProtocolMessageType('ModuleStart', (_message.Message,), dict(
  DESCRIPTOR = _MODULESTART,
  __module__ = 'lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:ModuleStart)
  ))
_sym_db.RegisterMessage(ModuleStart)

ModuleStop = _reflection.GeneratedProtocolMessageType('ModuleStop', (_message.Message,), dict(
  DESCRIPTOR = _MODULESTOP,
  __module__ = 'lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:ModuleStop)
  ))
_sym_db.RegisterMessage(ModuleStop)

ModuleRecover = _reflection.GeneratedProtocolMessageType('ModuleRecover', (_message.Message,), dict(
  DESCRIPTOR = _MODULERECOVER,
  __module__ = 'lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:ModuleRecover)
  ))
_sym_db.RegisterMessage(ModuleRecover)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTION,
  __module__ = 'lifecycle_pb2'
  # @@protoc_insertion_point(class_scope:Connection)
  ))
_sym_db.RegisterMessage(Connection)


# @@protoc_insertion_point(module_scope)
